using TMPro;
using UnityEngine;
using UnityEngine.InputSystem;

public class PlayerGeneral : MonoBehaviour
{
    #region References
    [Header("StateMachine")]
    StateMachine StateMachine;
    public StateMachine STATEMACHINE => StateMachine;

    StateCollection States;
    public StateCollection STATES => States;


    [Header("Componentes")]
    public Rigidbody Rigidbody;
    public Transform mainCamera;

    [Header("Configuration")]
    [SerializeField] PlayerConfiguration PlayerConfiguration;
    public PlayerConfiguration CONFIGURATION => PlayerConfiguration;


    [Header("Collider")]
    [SerializeField] PlayerCollision PlayerCollision;
    public PlayerCollision COLLISION => PlayerCollision;


    [Header("Inputs")]
    InputTransformer InputTransformer;
    public InputTransformer INPUTTRANSFORMER => InputTransformer;


    [Header("Movement")]
    PlayerMovement PlayerMovement;
    public PlayerMovement MOVEMENT => PlayerMovement;


    [Header("Feedback")]
    [SerializeField] PlayerFeedback PlayerFeedback;
    public PlayerFeedback FEEDBACK => PlayerFeedback;


    [Header("Animations")]
    [SerializeField] AnimationManager AnimationManager;
    public AnimationManager ANIMATION => AnimationManager;
    #endregion


    private void Awake()
    {
        StateMachine = new StateMachine();
        States = new StateCollection(this);
        InputTransformer = new InputTransformer();
        PlayerMovement = new PlayerMovement(Rigidbody, PlayerConfiguration);
    }

    void Start()
    {
        StateMachine.ChangeState(States.OnGroundState(StateMachine)); 
    }

    void Update() => StateMachine.Update();

    void FixedUpdate() => StateMachine.FixedUpdate();

    void LateUpdate() => StateMachine.LateUpdate();
}
